name: ci

on: workflow_dispatch

jobs:
  setup:
    name: "Checkout & generate changelog"
    runs-on: self-hosted

    outputs:
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: 'chore(release): {version}'
          release-count: 0

  build:
    name: "Build & Generate output"
    needs: [ setup ]
    runs-on: self-hosted

    steps:
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate

  release:
    name: "Create release"
    needs: [ build, setup ]
    if: ${{ needs.setup.outputs.skipped == 'false' }}
    runs-on: self-hosted

    steps:
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          path: './.output'
          type: 'zip'
          filename: 'output.zip'

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}
          files: output.zip
#
#  deploy:
#    name: "Deploy"
#    needs: [ build, setup ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Stop pm2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          # this script has to be joined with && before push
#          # I hate windows
#          script: |
#            whoami
#            dir
#            echo "Piss shit feed"


