name: ci

on: workflow_dispatch

jobs:
  test:
    name: "Checkout & setup node"
    runs-on: self-hosted

    env:
      piss: 'Piss Shit'

    steps:
      - run: |
          echo "$GITHUB_WORKSPACE"
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ACTOR"
          echo "$CI"
          echo "$piss"

      - run: echo "$GITHUB.REPOSITORY_OWNER"
      - run: echo "$GITHUB.GITHUB_WORKSPACE"

      - name: 'SHIT PISS'
        run: |
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"

      - name: Print environment variables
        uses: FranzDiebold/github-env-vars-action@v2
        run: |
          echo "CI_REPOSITORY_SLUG=$CI_REPOSITORY_SLUG"
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_OWNER_SLUG=$CI_REPOSITORY_OWNER_SLUG"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
          echo "CI_REPOSITORY_NAME_SLUG=$CI_REPOSITORY_NAME_SLUG"
          echo "CI_REPOSITORY=$CI_REPOSITORY"
          echo "CI_REF_SLUG=$CI_REF_SLUG"
          echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
          echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
          echo "CI_REF_NAME=$CI_REF_NAME"
          echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
          echo "CI_REF=$CI_REF"
          echo "CI_HEAD_REF_SLUG=$CI_HEAD_REF_SLUG"
          echo "CI_HEAD_REF=$CI_HEAD_REF"
          echo "CI_BASE_REF_SLUG=$CI_BASE_REF_SLUG"
          echo "CI_BASE_REF=$CI_BASE_REF"
          echo "CI_SHA_SHORT=$CI_SHA_SHORT"
          echo "CI_SHA=$CI_SHA"
          echo "CI_ACTOR=$CI_ACTOR"
          echo "CI_EVENT_NAME=$CI_EVENT_NAME"
          echo "CI_RUN_ID=$CI_RUN_ID"
          echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"
          echo "CI_WORKFLOW=$CI_WORKFLOW"
          echo "CI_ACTION=$CI_ACTION"

#jobs:
#  setup:
#    name: "Checkout & setup node"
#    runs-on: self-hosted
#
#    strategy:
#      matrix:
#        node-version: [16.x]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm install
#
#  changelog:
#    name: "Generate changelog"
#    needs: [ setup ]
#    runs-on: self-hosted
#
#    outputs:
#      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
#      tag: ${{ steps.changelog.outputs.tag }}
#      skipped: ${{ steps.changelog.outputs.skipped }}
#
#    steps:
#      - name: Generate Changelog
#        id: changelog
#        uses: TriPSs/conventional-changelog-action@v3
#        with:
#          git-message: 'chore(release): {version}'
#          release-count: 0
#
#  build:
#    name: "Build & Generate output"
#    needs: [ changelog ]
#    runs-on: self-hosted
#
#    steps:
#      - run: |
#          npm run build
#          npm run generate
#
#      - uses: montudor/action-zip@v1
#        with:
#          args: zip -qq -r dir.zip dir
#
#  release:
#    name: "Create release"
#    needs: [ build, changelog ]
#    if: ${{ needs.changelog.outputs.skipped == 'false' }}
#    runs-on: self-hosted
#
#    steps:
#      - uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ needs.changelog.outputs.tag }}
#          name: ${{ needs.changelog.outputs.tag }}
#          body: ${{ needs.changelog.outputs.clean_changelog }}
#          files: dist.zip
#
#  deploy:
#    name: "Deploy to PM2"
#    needs: [ build ]
#    runs-on: self-hosted


