name: ci

on: workflow_dispatch

jobs:
  setup:
    name: "Checkout, setup node & generate changelog"
    runs-on: self-hosted

    outputs:
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: 'chore(release): {version}'
          release-count: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

  build:
    name: "Build & Generate output"
    needs: [ setup ]
    runs-on: self-hosted

    steps:
      - run: |
          npm run build
          npm run generate

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r output.zip .output

  release:
    name: "Create release"
    needs: [ build, setup ]
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: self-hosted

    steps:
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}
          files: dist.zip
#
#  deploy:
#    name: "Deploy"
#    needs: [ build, setup ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Stop pm2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          # this script has to be joined with && before push
#          # I hate windows
#          script: |
#            whoami
#            dir
#            echo "Piss shit feed"


